/** Downtown MegaKit filenames used by street furniture jobs. */

export const CAST_KEYS = new Set([
  'stairsConcrete', 'stairsMarble',
  'railsConcrete', 'railsMarble', 'railsMetal',
  'railsConcreteS1', 'railsConcreteS2',
  'railsMarbleS1', 'railsMarbleS2',
  'railsMetalS1', 'railsMetalS2',
  'fireB', 'fireC', 'fireT',
  'planterC', 'planterL', 'planterR',
  'planterSC', 'planterSL', 'planterSR',
  'bollard', 'arch', 'colTrim',
  'entranceM21', 'entranceM22', 'entranceC22'
]);

export const FILES = {
  stairsConcrete: 'Stairs_Entrance_Concrete.gltf',
  stairsMarble: 'Stairs_Entrance_Marble.gltf',
  railsConcrete: 'Stairs_Rails_Concrete.gltf',
  railsMarble: 'Stairs_Rails_Marble.gltf',
  railsMetal: 'Stairs_Rails_Metal.gltf',
  railsConcreteS1: 'Stairs_Rails_Concrete_Straight_1.gltf',
  railsConcreteS2: 'Stairs_Rails_Concrete_Straight_2.gltf',
  railsMarbleS1: 'Stairs_Rails_Marble_Straight_1.gltf',
  railsMarbleS2: 'Stairs_Rails_Marble_Straight_2.gltf',
  railsMetalS1: 'Stairs_Rails_Metal_Straight_1.gltf',
  railsMetalS2: 'Stairs_Rails_Metal_Straight_2.gltf',
  // Four unique JadeGarden glTFs — each is a separate gltf:parse (MAP hitch).
  jadeV: 'Prop_Sign_JadeGarden_Vertical.gltf',
  jade: 'Prop_Sign_JadeGarden.gltf',
  jadeL: 'Prop_Sign_JadeGarden_Side_L.gltf',
  jadeR: 'Prop_Sign_JadeGarden_Side_R.gltf',
  bakery: 'Prop_Sign_Bakery.gltf',
  carmines: 'Prop_Sign_Carmines.gltf',
  carminesSide: 'Prop_Sign_Carmines_Side.gltf',
  deli: 'Prop_Sign_Deli.gltf',
  hannigan: 'Prop_Sign_Hannigan.gltf',
  mays: 'Prop_Sign_Mays.gltf',
  hwL: 'Prop_Sign_HW_Side_L.gltf',
  hwR: 'Prop_Sign_HW_Side_R.gltf',
  awning: 'Prop_Awning.gltf',
  awningLong: 'Prop_Awning_Long.gltf',
  awningBakery: 'Prop_Awning.gltf',
  awningCarmines: 'Prop_Awning.gltf',
  awningCarminesLong: 'Prop_Awning_Long.gltf',
  awningPub: 'Prop_Awning.gltf',
  awningPubLong: 'Prop_Awning_Long.gltf',
  fireB: 'Prop_FireEscape_Bottom.gltf',
  fireC: 'Prop_FireEscape_Center.gltf',
  fireT: 'Prop_FireEscape_Top.gltf',
  drain: 'Prop_Drain.gltf',
  bollard: 'Prop_Bollard.gltf',
  ac: 'Prop_ACUnit.gltf',
  manhole: 'Prop_ManholeCover.gltf',
  planterC: 'Prop_Planter_Center.gltf',
  planterL: 'Prop_Planter_Side_L.gltf',
  planterR: 'Prop_Planter_Side_R.gltf',
  planterSC: 'Prop_Planter_Small_Center.gltf',
  planterSL: 'Prop_Planter_Small_Side_L.gltf',
  planterSR: 'Prop_Planter_Small_Side_R.gltf',
  arch: 'Prop_ColumnArch.gltf',
  colTrim: 'Prop_Column_Trim.gltf',
  ornament2: 'Prop_Ornament_2.gltf',
  ornament3: 'Prop_Ornament_3.gltf',
  entranceM21: 'Entrance_Marble_2x1.gltf',
  entranceM22: 'Entrance_Marble_2x2.gltf',
  entranceC22: 'Entrance_Concrete_2x2.gltf',
  curve4s: 'Street_Curve_4Lane_Short_Curb.gltf',
  curve4l: 'Street_Curve_4Lane_Long_Curb.gltf',
  curve4short: 'Street_Curve_4LaneShort.gltf',
  curve4long: 'Street_Curve_4LaneLong.gltf',
  curve2: 'Street_Curve_2Lane.gltf',
  asphaltCurve2: 'Street_Asphalt_Curve_2Lane.gltf',
  asphaltCurve4s: 'Street_Asphalt_Curve_4Lane_Short.gltf',
  asphaltCurve4l: 'Street_Asphalt_Curve_4Lane_Long.gltf',
  decalCurve2: 'Decal_Curve_2Lane_Stripe.gltf',
  decalCurve4s: 'Decal_Curve_4LaneShort_Stripe.gltf',
  decalCurve4l: 'Decal_Curve_4LaneLong_Stripe.gltf',
  ramp: 'Sidewalk_CornerRamp_Round_3m.gltf'
};
